/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proj;

import org.junit.jupiter.api.Test;

import com.Driver;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Driver classUnderTest = new Driver();
        
    }
}
